### ISSUE TITLE
User settings

### ISSUE THREAD

**Issue by Schoggiweggli** [mddub/minimed-connect-to-nightscout#5]
I can't get this to work with node.js. Where do i need to set the username/password? i supposed in the run.js files var config section by replacing CARELINK_USERNAME, that doesn't seem to work because i always get this error:

`Error: Missing CareLink username
    at Object.<anonymous> (/xxx/xxx/minimed-connect-to-nightscout/run.js:32:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3`

**Comment by Schoggiweggli** [comment]
Figured it out after some time. It has to look like this:

`username: readEnv('CARELINK_USERNAME', 'unsernamegoeshere'),`
